// <auto-generated />
using System;
using DBKernel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBKernel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230131073804_AddTaskStateTable")]
    partial class AddTaskStateTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("DBKernel.Entity.TaskState", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskTicketGid")
                        .HasColumnType("TEXT");

                    b.HasKey("Gid");

                    b.HasIndex("TaskTicketGid")
                        .IsUnique();

                    b.ToTable("TaskStates");
                });

            modelBuilder.Entity("DBKernel.Entity.TaskTicket", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KigenBi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskStateGid")
                        .HasColumnType("TEXT");

                    b.Property<int>("TourokuBi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Gid");

                    b.ToTable("TaskTickets");
                });

            modelBuilder.Entity("DBKernel.Entity.TaskState", b =>
                {
                    b.HasOne("DBKernel.Entity.TaskTicket", "TaskTicket")
                        .WithOne("TaskState")
                        .HasForeignKey("DBKernel.Entity.TaskState", "TaskTicketGid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskTicket");
                });

            modelBuilder.Entity("DBKernel.Entity.TaskTicket", b =>
                {
                    b.Navigation("TaskState")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
