// <auto-generated />
using System;
using DBKernel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBKernel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("TaskWithYou.Shared.Model.Cluster", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Gid");

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("TaskWithYou.Shared.Model.TaskState", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Gid");

                    b.ToTable("TaskStates");
                });

            modelBuilder.Entity("TaskWithYou.Shared.Model.TaskTicket", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CardGid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClusterGid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTodayTask")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KigenBi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StateGid")
                        .HasColumnType("TEXT");

                    b.Property<int>("TourokuBi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Gid");

                    b.ToTable("TaskTickets");
                });

            modelBuilder.Entity("TaskWithYou.Shared.Model.TicketCard", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskTicket")
                        .HasColumnType("TEXT");

                    b.Property<float>("XCoordinate")
                        .HasColumnType("REAL");

                    b.Property<float>("YCoordinate")
                        .HasColumnType("REAL");

                    b.HasKey("Gid");

                    b.ToTable("TicketCards");
                });
#pragma warning restore 612, 618
        }
    }
}
